// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balance.proto

package com.betPawa.bitWallet;

public final class IBalance {
  private IBalance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BalanceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BalanceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code BalanceRequest}
   */
  public  static final class BalanceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BalanceRequest)
      BalanceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BalanceRequest.newBuilder() to construct.
    private BalanceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BalanceRequest() {
      userId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BalanceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.betPawa.bitWallet.IBalance.internal_static_BalanceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.betPawa.bitWallet.IBalance.internal_static_BalanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.betPawa.bitWallet.IBalance.BalanceRequest.class, com.betPawa.bitWallet.IBalance.BalanceRequest.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.betPawa.bitWallet.IBalance.BalanceRequest)) {
        return super.equals(obj);
      }
      com.betPawa.bitWallet.IBalance.BalanceRequest other = (com.betPawa.bitWallet.IBalance.BalanceRequest) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.betPawa.bitWallet.IBalance.BalanceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BalanceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BalanceRequest)
        com.betPawa.bitWallet.IBalance.BalanceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.betPawa.bitWallet.IBalance.BalanceRequest.class, com.betPawa.bitWallet.IBalance.BalanceRequest.Builder.class);
      }

      // Construct using com.betPawa.bitWallet.IBalance.BalanceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceRequest_descriptor;
      }

      public com.betPawa.bitWallet.IBalance.BalanceRequest getDefaultInstanceForType() {
        return com.betPawa.bitWallet.IBalance.BalanceRequest.getDefaultInstance();
      }

      public com.betPawa.bitWallet.IBalance.BalanceRequest build() {
        com.betPawa.bitWallet.IBalance.BalanceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.betPawa.bitWallet.IBalance.BalanceRequest buildPartial() {
        com.betPawa.bitWallet.IBalance.BalanceRequest result = new com.betPawa.bitWallet.IBalance.BalanceRequest(this);
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.betPawa.bitWallet.IBalance.BalanceRequest) {
          return mergeFrom((com.betPawa.bitWallet.IBalance.BalanceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.betPawa.bitWallet.IBalance.BalanceRequest other) {
        if (other == com.betPawa.bitWallet.IBalance.BalanceRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.betPawa.bitWallet.IBalance.BalanceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.betPawa.bitWallet.IBalance.BalanceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BalanceRequest)
    }

    // @@protoc_insertion_point(class_scope:BalanceRequest)
    private static final com.betPawa.bitWallet.IBalance.BalanceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.betPawa.bitWallet.IBalance.BalanceRequest();
    }

    public static com.betPawa.bitWallet.IBalance.BalanceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BalanceRequest>
        PARSER = new com.google.protobuf.AbstractParser<BalanceRequest>() {
      public BalanceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BalanceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BalanceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BalanceRequest> getParserForType() {
      return PARSER;
    }

    public com.betPawa.bitWallet.IBalance.BalanceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BalanceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BalanceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    java.util.List<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement> 
        getStatementList();
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    com.betPawa.bitWallet.IBalance.BalanceResponse.Statement getStatement(int index);
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    int getStatementCount();
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    java.util.List<? extends com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder> 
        getStatementOrBuilderList();
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder getStatementOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BalanceResponse}
   */
  public  static final class BalanceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BalanceResponse)
      BalanceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BalanceResponse.newBuilder() to construct.
    private BalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BalanceResponse() {
      userId_ = 0L;
      statement_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BalanceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                statement_ = new java.util.ArrayList<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement>();
                mutable_bitField0_ |= 0x00000002;
              }
              statement_.add(
                  input.readMessage(com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          statement_ = java.util.Collections.unmodifiableList(statement_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.betPawa.bitWallet.IBalance.BalanceResponse.class, com.betPawa.bitWallet.IBalance.BalanceResponse.Builder.class);
    }

    public interface StatementOrBuilder extends
        // @@protoc_insertion_point(interface_extends:BalanceResponse.Statement)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string currencyType = 1;</code>
       */
      java.lang.String getCurrencyType();
      /**
       * <code>string currencyType = 1;</code>
       */
      com.google.protobuf.ByteString
          getCurrencyTypeBytes();

      /**
       * <code>double amount = 2;</code>
       */
      double getAmount();
    }
    /**
     * Protobuf type {@code BalanceResponse.Statement}
     */
    public  static final class Statement extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:BalanceResponse.Statement)
        StatementOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Statement.newBuilder() to construct.
      private Statement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Statement() {
        currencyType_ = "";
        amount_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Statement(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                currencyType_ = s;
                break;
              }
              case 17: {

                amount_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_Statement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_Statement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.class, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder.class);
      }

      public static final int CURRENCYTYPE_FIELD_NUMBER = 1;
      private volatile java.lang.Object currencyType_;
      /**
       * <code>string currencyType = 1;</code>
       */
      public java.lang.String getCurrencyType() {
        java.lang.Object ref = currencyType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyType_ = s;
          return s;
        }
      }
      /**
       * <code>string currencyType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyTypeBytes() {
        java.lang.Object ref = currencyType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int AMOUNT_FIELD_NUMBER = 2;
      private double amount_;
      /**
       * <code>double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getCurrencyTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyType_);
        }
        if (amount_ != 0D) {
          output.writeDouble(2, amount_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getCurrencyTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyType_);
        }
        if (amount_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, amount_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.betPawa.bitWallet.IBalance.BalanceResponse.Statement)) {
          return super.equals(obj);
        }
        com.betPawa.bitWallet.IBalance.BalanceResponse.Statement other = (com.betPawa.bitWallet.IBalance.BalanceResponse.Statement) obj;

        boolean result = true;
        result = result && getCurrencyType()
            .equals(other.getCurrencyType());
        result = result && (
            java.lang.Double.doubleToLongBits(getAmount())
            == java.lang.Double.doubleToLongBits(
                other.getAmount()));
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CURRENCYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrencyType().hashCode();
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAmount()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.betPawa.bitWallet.IBalance.BalanceResponse.Statement prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code BalanceResponse.Statement}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:BalanceResponse.Statement)
          com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_Statement_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_Statement_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.class, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder.class);
        }

        // Construct using com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          currencyType_ = "";

          amount_ = 0D;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_Statement_descriptor;
        }

        public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement getDefaultInstanceForType() {
          return com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.getDefaultInstance();
        }

        public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement build() {
          com.betPawa.bitWallet.IBalance.BalanceResponse.Statement result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement buildPartial() {
          com.betPawa.bitWallet.IBalance.BalanceResponse.Statement result = new com.betPawa.bitWallet.IBalance.BalanceResponse.Statement(this);
          result.currencyType_ = currencyType_;
          result.amount_ = amount_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.betPawa.bitWallet.IBalance.BalanceResponse.Statement) {
            return mergeFrom((com.betPawa.bitWallet.IBalance.BalanceResponse.Statement)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.betPawa.bitWallet.IBalance.BalanceResponse.Statement other) {
          if (other == com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.getDefaultInstance()) return this;
          if (!other.getCurrencyType().isEmpty()) {
            currencyType_ = other.currencyType_;
            onChanged();
          }
          if (other.getAmount() != 0D) {
            setAmount(other.getAmount());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.betPawa.bitWallet.IBalance.BalanceResponse.Statement parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.betPawa.bitWallet.IBalance.BalanceResponse.Statement) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object currencyType_ = "";
        /**
         * <code>string currencyType = 1;</code>
         */
        public java.lang.String getCurrencyType() {
          java.lang.Object ref = currencyType_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            currencyType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string currencyType = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCurrencyTypeBytes() {
          java.lang.Object ref = currencyType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            currencyType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string currencyType = 1;</code>
         */
        public Builder setCurrencyType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          currencyType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string currencyType = 1;</code>
         */
        public Builder clearCurrencyType() {
          
          currencyType_ = getDefaultInstance().getCurrencyType();
          onChanged();
          return this;
        }
        /**
         * <code>string currencyType = 1;</code>
         */
        public Builder setCurrencyTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          currencyType_ = value;
          onChanged();
          return this;
        }

        private double amount_ ;
        /**
         * <code>double amount = 2;</code>
         */
        public double getAmount() {
          return amount_;
        }
        /**
         * <code>double amount = 2;</code>
         */
        public Builder setAmount(double value) {
          
          amount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double amount = 2;</code>
         */
        public Builder clearAmount() {
          
          amount_ = 0D;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:BalanceResponse.Statement)
      }

      // @@protoc_insertion_point(class_scope:BalanceResponse.Statement)
      private static final com.betPawa.bitWallet.IBalance.BalanceResponse.Statement DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.betPawa.bitWallet.IBalance.BalanceResponse.Statement();
      }

      public static com.betPawa.bitWallet.IBalance.BalanceResponse.Statement getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Statement>
          PARSER = new com.google.protobuf.AbstractParser<Statement>() {
        public Statement parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Statement(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Statement> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Statement> getParserForType() {
        return PARSER;
      }

      public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int STATEMENT_FIELD_NUMBER = 2;
    private java.util.List<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement> statement_;
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    public java.util.List<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement> getStatementList() {
      return statement_;
    }
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    public java.util.List<? extends com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder> 
        getStatementOrBuilderList() {
      return statement_;
    }
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    public int getStatementCount() {
      return statement_.size();
    }
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement getStatement(int index) {
      return statement_.get(index);
    }
    /**
     * <code>repeated .BalanceResponse.Statement statement = 2;</code>
     */
    public com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder getStatementOrBuilder(
        int index) {
      return statement_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      for (int i = 0; i < statement_.size(); i++) {
        output.writeMessage(2, statement_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      for (int i = 0; i < statement_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, statement_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.betPawa.bitWallet.IBalance.BalanceResponse)) {
        return super.equals(obj);
      }
      com.betPawa.bitWallet.IBalance.BalanceResponse other = (com.betPawa.bitWallet.IBalance.BalanceResponse) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getStatementList()
          .equals(other.getStatementList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      if (getStatementCount() > 0) {
        hash = (37 * hash) + STATEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getStatementList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.betPawa.bitWallet.IBalance.BalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.betPawa.bitWallet.IBalance.BalanceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BalanceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BalanceResponse)
        com.betPawa.bitWallet.IBalance.BalanceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.betPawa.bitWallet.IBalance.BalanceResponse.class, com.betPawa.bitWallet.IBalance.BalanceResponse.Builder.class);
      }

      // Construct using com.betPawa.bitWallet.IBalance.BalanceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStatementFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        if (statementBuilder_ == null) {
          statement_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          statementBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.betPawa.bitWallet.IBalance.internal_static_BalanceResponse_descriptor;
      }

      public com.betPawa.bitWallet.IBalance.BalanceResponse getDefaultInstanceForType() {
        return com.betPawa.bitWallet.IBalance.BalanceResponse.getDefaultInstance();
      }

      public com.betPawa.bitWallet.IBalance.BalanceResponse build() {
        com.betPawa.bitWallet.IBalance.BalanceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.betPawa.bitWallet.IBalance.BalanceResponse buildPartial() {
        com.betPawa.bitWallet.IBalance.BalanceResponse result = new com.betPawa.bitWallet.IBalance.BalanceResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.userId_ = userId_;
        if (statementBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            statement_ = java.util.Collections.unmodifiableList(statement_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.statement_ = statement_;
        } else {
          result.statement_ = statementBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.betPawa.bitWallet.IBalance.BalanceResponse) {
          return mergeFrom((com.betPawa.bitWallet.IBalance.BalanceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.betPawa.bitWallet.IBalance.BalanceResponse other) {
        if (other == com.betPawa.bitWallet.IBalance.BalanceResponse.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (statementBuilder_ == null) {
          if (!other.statement_.isEmpty()) {
            if (statement_.isEmpty()) {
              statement_ = other.statement_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStatementIsMutable();
              statement_.addAll(other.statement_);
            }
            onChanged();
          }
        } else {
          if (!other.statement_.isEmpty()) {
            if (statementBuilder_.isEmpty()) {
              statementBuilder_.dispose();
              statementBuilder_ = null;
              statement_ = other.statement_;
              bitField0_ = (bitField0_ & ~0x00000002);
              statementBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStatementFieldBuilder() : null;
            } else {
              statementBuilder_.addAllMessages(other.statement_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.betPawa.bitWallet.IBalance.BalanceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.betPawa.bitWallet.IBalance.BalanceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement> statement_ =
        java.util.Collections.emptyList();
      private void ensureStatementIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          statement_ = new java.util.ArrayList<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement>(statement_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.betPawa.bitWallet.IBalance.BalanceResponse.Statement, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder, com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder> statementBuilder_;

      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public java.util.List<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement> getStatementList() {
        if (statementBuilder_ == null) {
          return java.util.Collections.unmodifiableList(statement_);
        } else {
          return statementBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public int getStatementCount() {
        if (statementBuilder_ == null) {
          return statement_.size();
        } else {
          return statementBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement getStatement(int index) {
        if (statementBuilder_ == null) {
          return statement_.get(index);
        } else {
          return statementBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder setStatement(
          int index, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement value) {
        if (statementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatementIsMutable();
          statement_.set(index, value);
          onChanged();
        } else {
          statementBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder setStatement(
          int index, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder builderForValue) {
        if (statementBuilder_ == null) {
          ensureStatementIsMutable();
          statement_.set(index, builderForValue.build());
          onChanged();
        } else {
          statementBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder addStatement(com.betPawa.bitWallet.IBalance.BalanceResponse.Statement value) {
        if (statementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatementIsMutable();
          statement_.add(value);
          onChanged();
        } else {
          statementBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder addStatement(
          int index, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement value) {
        if (statementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatementIsMutable();
          statement_.add(index, value);
          onChanged();
        } else {
          statementBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder addStatement(
          com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder builderForValue) {
        if (statementBuilder_ == null) {
          ensureStatementIsMutable();
          statement_.add(builderForValue.build());
          onChanged();
        } else {
          statementBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder addStatement(
          int index, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder builderForValue) {
        if (statementBuilder_ == null) {
          ensureStatementIsMutable();
          statement_.add(index, builderForValue.build());
          onChanged();
        } else {
          statementBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder addAllStatement(
          java.lang.Iterable<? extends com.betPawa.bitWallet.IBalance.BalanceResponse.Statement> values) {
        if (statementBuilder_ == null) {
          ensureStatementIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, statement_);
          onChanged();
        } else {
          statementBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder clearStatement() {
        if (statementBuilder_ == null) {
          statement_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          statementBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public Builder removeStatement(int index) {
        if (statementBuilder_ == null) {
          ensureStatementIsMutable();
          statement_.remove(index);
          onChanged();
        } else {
          statementBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder getStatementBuilder(
          int index) {
        return getStatementFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder getStatementOrBuilder(
          int index) {
        if (statementBuilder_ == null) {
          return statement_.get(index);  } else {
          return statementBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public java.util.List<? extends com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder> 
           getStatementOrBuilderList() {
        if (statementBuilder_ != null) {
          return statementBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(statement_);
        }
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder addStatementBuilder() {
        return getStatementFieldBuilder().addBuilder(
            com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.getDefaultInstance());
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder addStatementBuilder(
          int index) {
        return getStatementFieldBuilder().addBuilder(
            index, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.getDefaultInstance());
      }
      /**
       * <code>repeated .BalanceResponse.Statement statement = 2;</code>
       */
      public java.util.List<com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder> 
           getStatementBuilderList() {
        return getStatementFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.betPawa.bitWallet.IBalance.BalanceResponse.Statement, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder, com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder> 
          getStatementFieldBuilder() {
        if (statementBuilder_ == null) {
          statementBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.betPawa.bitWallet.IBalance.BalanceResponse.Statement, com.betPawa.bitWallet.IBalance.BalanceResponse.Statement.Builder, com.betPawa.bitWallet.IBalance.BalanceResponse.StatementOrBuilder>(
                  statement_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          statement_ = null;
        }
        return statementBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BalanceResponse)
    }

    // @@protoc_insertion_point(class_scope:BalanceResponse)
    private static final com.betPawa.bitWallet.IBalance.BalanceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.betPawa.bitWallet.IBalance.BalanceResponse();
    }

    public static com.betPawa.bitWallet.IBalance.BalanceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BalanceResponse>
        PARSER = new com.google.protobuf.AbstractParser<BalanceResponse>() {
      public BalanceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BalanceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BalanceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BalanceResponse> getParserForType() {
      return PARSER;
    }

    public com.betPawa.bitWallet.IBalance.BalanceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BalanceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BalanceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BalanceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BalanceResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BalanceResponse_Statement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BalanceResponse_Statement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbalance.proto\" \n\016BalanceRequest\022\016\n\006use" +
      "rId\030\001 \001(\003\"\203\001\n\017BalanceResponse\022\016\n\006userId\030" +
      "\001 \001(\003\022-\n\tstatement\030\002 \003(\0132\032.BalanceRespon" +
      "se.Statement\0321\n\tStatement\022\024\n\014currencyTyp" +
      "e\030\001 \001(\t\022\016\n\006amount\030\002 \001(\0012H\n\030BitWallletBal" +
      "anceService\022,\n\007Balance\022\017.BalanceRequest\032" +
      "\020.BalanceResponseB!\n\025com.betPawa.bitWall" +
      "etB\010IBalanceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BalanceRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_BalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BalanceResponse_descriptor,
        new java.lang.String[] { "UserId", "Statement", });
    internal_static_BalanceResponse_Statement_descriptor =
      internal_static_BalanceResponse_descriptor.getNestedTypes().get(0);
    internal_static_BalanceResponse_Statement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BalanceResponse_Statement_descriptor,
        new java.lang.String[] { "CurrencyType", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
