// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bit-wallet-server.proto

package com.betPawa.bitWallet;

public final class IServer {
  private IServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027bit-wallet-server.proto\032\027bitWallet.dep" +
      "osit.proto\032\027bitWallet.balance.proto\032\030bit" +
      "Wallet.withdraw.proto2\237\001\n\021BitWallletServ" +
      "ice\022+\n\007Deposit\022\017.DepositRequest\032\017.Emplty" +
      "Response\022,\n\007Balance\022\017.BalanceRequest\032\020.B" +
      "alanceResponse\022/\n\010Withdraw\022\020.WithdrawReq" +
      "uest\032\021.WithdrawResponseB \n\025com.betPawa.b" +
      "itWalletB\007IServerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.betPawa.bitWallet.IDeposit.getDescriptor(),
          com.betPawa.bitWallet.IBalance.getDescriptor(),
          com.betPawa.bitWallet.IWithdraw.getDescriptor(),
        }, assigner);
    com.betPawa.bitWallet.IDeposit.getDescriptor();
    com.betPawa.bitWallet.IBalance.getDescriptor();
    com.betPawa.bitWallet.IWithdraw.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
